### ISSUE TITLE
Gem doesn't work at production ENV. 

### ISSUE THREAD

**Issue by mrmsaib** [kbaum/browser-timezone-rails#13]
This Gem works like at development environment. However, it doesn't work at all when I uploaded my app to aws amazon. Any Idea ? Thanks.

**Comment by kbaum** [comment]
My guess would be that your local system time zone matches your browsers locally so you only notice the issue when you are in production.  


How do you know it's not working?  Are you using Time.zone.now or Time.now? Just some ideas..




Thx!

**Comment by mrmsaib** [comment]
My timezone is MST and rails is UTC. so the problem starts at 5: pm MST time when the next day starts at UTC time;
After 5:00pm mountain time, the problem appears at production, however everything is fine at development. 

Baseically at  index page, it shows posts under two categories "today's posts and yesterday's post", the code is below 

I'm using Date.today & Date.yesterday codes.

**Comment by kbaum** [comment]
It doesn’t look like Date.today uses the rails time zone.  On a plane right now so i can’t research much more but was able to reproduce this within rails console:





[1] pry(main)> Date.today

Mon, 19 Jan 2015

[2] pry(main)> Time.zone.now

Tue, 20 Jan 2015 01:25:04 UTC +00:00




Time.zone.today works nicely it seems:





[24] pry(main)> Time.zone.today

Tue, 20 Jan 2015




For yesterday you could just take a day away:





[25] pry(main)> Time.zone.today - 1.day

Mon, 19 Jan 2015








Karl Baum
Chief Technology Officer


View The Space


O: 917-439-1791



142 West 36th Street 

New York, NY 10018

www.ViewTheSpace.com

**Comment by mrmsaib** [comment]
Thanks for your comment Karl. 

The thing is i am using your gem to show local users their local date, This is the code I'm using

<td><h4><%= l Date.today, format: '%A ,%d %B %Y'  %></h4></td>
<td><h4><%= l Date.yesterday, format: '%A ,%d %B %Y'  %></h4></td>

On development, your gem works perfectly fine and the date appears on Mountain time instead of rails zone.  Probably there's something missing in my code!!!

Thanks, 
MO.

**Comment by mrmsaib** [comment]
Hey Karl, never-mind. I used Time.zone.today instead of Date.today and everything work like charm. I know this code before but i never thought it will be the solution, even i still don't understand. probably because of 3 days non stop of sleep lol

Thank you so for taking the time to assist me, much appreciated :)

**Comment by kbaum** [comment]
Glad i could help!  Time zones can be confusing in rails.  Some methods respect the time zone setting while others like Date.today use the system time zone.




There’s a good rails casts about timezones in rails:




http://railscasts.com/episodes/106-time-zones-revised?view=comments





It’s old, but it’s where i learned this stuff.








Karl Baum
Chief Technology Officer


View The Space


O: 917-439-1791



142 West 36th Street 

New York, NY 10018

www.ViewTheSpace.com

**Comment by mrmsaib** [comment]
Thanks Carl.
