### ISSUE TITLE
Different list of Time Zones in Production vs Development

### ISSUE THREAD

**Issue by sealabcore** [kbaum/browser-timezone-rails#15]
Using the same browser / same ruby version / browser-timezone-rails version / rails version.

```ruby
form.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {default: (current_user.time_zone || "Pacific Time (US & Canada)")}
```

Returns extra time zones in production that aren't seen in my development environment.

For example, in development I only see the time zone "Sydney", but in production I am seeing both "Australia/Sydney" and "Sydney" as two different options.
https://www.dropbox.com/s/qxexgahreb3eemf/Screenshot%202015-02-10%2014.59.57.png?dl=0

Any thoughts as to why this is happening?

**Comment by kbaum** [comment]
Not sure honestly.. my guess is that it has something to do with the OS setup.

**Comment by sealabcore** [comment]
Yeah, right after I opened this I assumed it had to do with the OS as well. Thanks! Going to close this ticket.
