### ISSUE TITLE
After adding it to gem file the page does not render.

### ISSUE THREAD

**Issue by jbmyid** [kbaum/browser-timezone-rails#16]
I have just added the gem in Gemfile but when bundle and run the server and the page doesn't display even single html content. 
Don't know whats wrong.

Rails version: '4.1.0'

**Comment by kbaum** [comment]
Is there error information in your rails server log?

**Comment by jbmyid** [comment]
No. No error on logs either.

**Comment by kbaum** [comment]
I think this has been addressed with latest release.
