### ISSUE TITLE
Nothing seems to work for me on Rails 4.1.4

### ISSUE THREAD

**Issue by AndreasHeiberg** [kbaum/browser-timezone-rails#19]
I included the gem, did bundle install and added the imports to application.js.

My application threw exceptions saying the js files didn't exist. I reluctantly went about and created the js files in my vendor folder my self.

Now `cookies["browser.timezone"]` is indeed set to `"America/Los_Angeles"`, but `Time.zone.name` returns `"UTC"`

**Comment by kbaum** [comment]
I think this has been addressed as I am using this in rails 4.2.X.
