### ISSUE TITLE
Fix deprecations notices for Rails 5.0.0beta1

### ISSUE THREAD

**Issue by danielrsmith** [kbaum/browser-timezone-rails#22]
`DEPRECATION WARNING: around_filter is deprecated and will be removed in Rails 5.1. Use around_action instead.`

**Comment by kbaum** [comment]
But then it won't work in rails 3?

**Comment by danielrsmith** [comment]
Well Rails 3 hits end of life as soon as Rails 5 is released.  Maybe the next version needs to be Rails 4+ and anyone who uses Rails 3 needs to use an older version of the gem.

**Comment by kbaum** [comment]
Good call!
