### ISSUE TITLE
couldn't find file 'jquery.cookie'

### ISSUE THREAD

**Issue by wenwei63029869** [kbaum/browser-timezone-rails#23]
I follow the install instruction and bundle. However, when I load my website, it gave an error as below:

couldn't find file 'jquery.cookie' with type 'application/javascript'

I was wondering what is going on. I try to manually add 'jquery-cookie-rails' gem, but the error still occurred.

Thank you!

**Comment by kbaum** [comment]
This has been addressed.

**Comment by JeffWaltzer** [comment]
I'm getting this error with version 1.0.1.   Where was this addressed?

**Comment by nheinrich** [comment]
I'm also getting this error with version 1.0.1.

**Comment by BenTalagan** [comment]
In case anyone stumbles across this issue, the documentation has been updated, now it should be:

```
//= require js.cookie
```

not

```
//= require jquery.cookie
```
