### ISSUE TITLE
Please versionize your gem

### ISSUE THREAD

**Issue by gauthier-delacroix** [kbaum/browser-timezone-rails#30]
Your recent replacement of `jquery-cookie-rails` by `js_cookie_rails` caused multiple errors (#23, #28, #29).

As you don't tag/versionize your gem, a simple `bundle update` causes the gem to be updated without notice to a malfunctioning version.

Could you use tags and versionize your releases to avoid this kind of problems ?
Please also not that asking to change the require statement in application.js is a breaking change that should have caused a major version bump.

Thanks !

**Comment by kbaum** [comment]
All makes sense. Are you referencing the github version in your Gemfile? I
don't remember pushing this to rubygems.
