### ISSUE TITLE
Cookie if user changes time zones

### ISSUE THREAD

**Issue by ACPK** [kbaum/browser-timezone-rails#35]
If the cookie is set for 365 days, what happens when the user travels to a different time zone?

**Comment by DanBonehill** [comment]
The README says:
> The cookie is set each full page request and lives for 365 days

I understand that to mean, the cookie is set each time a page request is made. So if a user travels to a new time zone the cookie should be changed when they make their first page request in that new time zone.

I may be wrong, but that's how I interpret it. I'm travelling to a different time zone next week. I'll try it out and report back :)

**Comment by kbaum** [comment]
It resets every full page request.. so a single page app requires a full
page request.
