### ISSUE TITLE
Master no longer works with Rails 3

### ISSUE THREAD

**Issue by joe1chen** [kbaum/browser-timezone-rails#38]
It looks like commit dbba0a4a40413c6d99e4ddf2c4d1c123bf22be63 introduced a reference to `prepend_around_action` which is only available for Rails 4.  In Rails 3, this is `prepend_around_filter`.

Not sure what the best solution is here. You could have 2 branches: master and rails-3 branch.

At the very least the gemspec needs to be updated to show that Rails 4 is required.

**Comment by rylanb** [comment]
It sucks to admit, but I have this issue, as well.

**Comment by rylanb** [comment]
`gem 'browser-timezone-rails', '~> 0.2.00'` fixed it for me for now.

**Comment by texpert** [comment]
Please, look at a PR for re-enabling working with Rails 3 - https://github.com/kbaum/browser-timezone-rails/pull/42

**Comment by kbaum** [comment]
Fixed by #42 .
