### ISSUE TITLE
Mark cookie as secure

### ISSUE THREAD

**Issue by BiggerNoise** [kbaum/browser-timezone-rails#40]
This is silliness being imposed upon us by an automated auditor. The auditor is complaining that the cookie is not marked secure.

Obviously, there's no security benefit to marking a cookie containing the client's timezone as secure, but we may find it easier to roll our eyes and make the change than to explain why they're wrong to raise the issue.

All that said, would you be open to a pull request that marked the cookie as secure if the gem is running in a secure environment (https required)? I think I could just change  browser-timezone-rails/app/assets/javascripts/browser_timezone_rails/set_time_zone.js to a js.erb file and add the option based upon the configuration.

If that sounds like something you'd accept, I should be able to get you a P/R in a day.

**Comment by kbaum** [comment]
Sure! I think we could look at the rails setting force_ssl.
