### ISSUE TITLE
Require js with webpacker?

### ISSUE THREAD

**Issue by cedm** [kbaum/browser-timezone-rails#44]
How to require `js.cookie` and `browser_timezone_rails/set_time_zone` when using webpacker? I keep getting the following error:

```
ERROR in ./app/javascript/packs/application.js
21:35:26 webpack.1 | Module not found: Error: Can't resolve 'js.cookie'
```

I'm confused...

**Comment by kbaum** [comment]
I haven't tried using browser_timezone_rails with webpacker. Are you using rails 6?

**Comment by cedm** [comment]
I'm actually using Rails 5.2, but that shouldn't make any difference with Rails 6. That said, after looking into the gem's code, I realized how simple it was and just copied that tiny bit of JS into my application code. Problem solved for me.

**Comment by kbaum** [comment]
Makes sense. I am honestly not using this gem anymore. It’s kind of been surviving due to pull requests from community. Should ask if someone else wants to maintain.
